### ISSUE TITLE
The normal maps for TNT

### ISSUE THREAD

**Issue by GuangyuWang99** [Wuuu3511/GoMVS#1]
Hi, 

Thanks for the excellent work! However, I found all provided monocular normal data (e.g., in this [link](https://pan.baidu.com/s/17i2wOzl0s0uwF2SMXL3tnQ?pwd=f67q)) seems to be broken. Could you help check it and upload it again? 

Thanks in advance!

**Comment by GuangyuWang99** [comment]
Besides, I'm wondering whether this method is **robust** to the normal priors. That is, once the model is pretrained using Ominidata normals, will the results deteriorate when inference with normals from other high quality monocular models (e.g., DepthAnything, Marigold, DSINE), due to sorts of distribution shift?

**Comment by Wuuu3511** [comment]
> Besides, I'm wondering whether this method is **robust** to the normal priors. That is, once the model is pretrained using Ominidata normals, will the results deteriorate when inference with normals from other high quality monocular models (e.g., DepthAnything, Marigold, DSINE), due to sorts of distribution shift?

Thank you for your attention to our work.

I have updated the Baidu Cloud link for the TNT normal data: https://pan.baidu.com/s/1Vep8lANnx3UqBNy4ZMXatQ?pwd=et97.

We have not tested normals generated by other monocular networks. Perhaps similar normal prediction methods could yield similar results.
