### ISSUE TITLE
How is `min_depth` and `depth_interval` determined?

### ISSUE THREAD

**Issue by penguinflys** [Wuuu3511/GoMVS#14]
Hello, 

Thanks a lot for your excellent contribution! It shows very accurate depth in high confidence regions.

On the application of other datasets (LLFF & Mip 360 V2) I had to determine `min_depth` `depth_interval` as well as `depth_max` etc.

Can you please share how are those values applied in your practice? I see that you put the value in the `**_cam.txt` but i cannot locate the process to produce it.

**Comment by Wuuu3511** [comment]
Hello, the depth range is determined by the sparse points reconstructed through COLMAP. You can refer to https://github.com/FangjinhuaWang/PatchmatchNet/blob/main/colmap_input.py.
